添加iproute2程序以供vip挂载漂移使用
bitnami/bitnami-docker-pgpool pull request #62
Opened 2021-09-28 09:00 UTC by s154050727

搭建高可用集群时无法挂载vip，经查证该镜像未提供ip或ifconfig命令，导致执行挂载vip命令时失败

2021-09-29 12:08 UTC, carrodher requested changes

2021-09-29 12:08 UTC, carrodher commented on 4/debian-10/Dockerfile
> +RUN apt-get update && apt-get install iproute2
Can you explain (in English) what is your use case to add this system package to the container image? Apart from that, after our evaluation and in case we consider adding it, the addition should be done by using the `install_packages` binary (see suggestion)

```suggestion
RUN install_packages acl ca-certificates curl gzip iproute2 ldap-utils libaudit1 libbsd0 libc6 libcap-ng0 libedit2 libffi6 libgcc1 libgmp10 libgnutls30 libhogweed4 libicu63 libidn2-0 libldap-2.4-2 liblzma5 libnettle6 libnss-ldapd libp11-kit0 libpam-ldapd libpam0g libsasl2-2 libssl1.1 libstdc++6 libtasn1-6 libtinfo6 libunistring2 libuuid1 libxml2 libxslt1.1 nslcd procps tar zlib1g
```

2021-09-30 01:17 UTC, s154050727 commented on 4/debian-10/Dockerfile
> +RUN apt-get update && apt-get install iproute2
When I deploy a pgpool high-availability cluster, I can't add a virtual ip to any network device because there isn't ip command in the bitnami-docker-pgpool image. 

This is my pgpool.conf.
# - Virtual IP control Setting -

delegate_IP = '192.168.1.14'
                                    # delegate IP address
                                    # If this is empty, virtual IP never bring up.
                                    # (change requires restart)
if_cmd_path = '/sbin'
                                    # path to the directory where if_up/down_cmd exists
                                    # If if_up/down_cmd starts with "/", if_cmd_path will be ignored.
                                    # (change requires restart)
if_up_cmd = '/sbin/ip addr add $_IP_$/24 dev eth0 label eth0:1'
                                    # startup delegate IP command
                                    # (change requires restart)
if_down_cmd = '/sbin/ip addr del $_IP_$/24 dev eth0'
                                    # shutdown delegate IP command
                                    # (change requires restart)
arping_path = '/usr/sbin'
                                    # arping command path
                                    # If arping_cmd starts with "/", if_cmd_path will be ignored.
                                    # (change requires restart)
arping_cmd = '/usr/sbin/arping -U $_IP_$ -w 1 -I eth0'
                                    # arping command
                                    # (change requires restart)

2021-10-04 16:06 UTC, randradas commented
please @s154050727 would you take a look to the changes requested by @carrodher?. Thank you!

2021-11-16 01:23 UTC, closed without merging