Add ENV to support setting reserved_connections.
bitnami/bitnami-docker-pgpool pull request #73
Opened 2021-12-13 22:50 UTC by meln5674

**Description of the change**
Enable setting reserved_connection in pgpool.conf via an ENV, similar to how, e.g. num_init_children is handled.

**Benefits**

This is to support a similar feature in the helm charts.

**Possible drawbacks**

**Applicable issues**

See [This comment](https://github.com/bitnami/charts/issues/6094#issuecomment-991395399) for context

**Additional information**

Needed for [This PR](https://github.com/bitnami/charts/pull/8398)

2021-12-14 09:57 UTC, rafariossaa approved these changes
Hi,
  Thanks for providing this.

2021-12-14 10:08 UTC, rafariossaa requested changes

2021-12-14 10:08 UTC, rafariossaa commented on README.md
> +- `PGPOOL_RESERVED_CONNECTIONS: When this parameter is set to 1 or greater, incoming connections from clients are not accepted with error message "Sorry, too many clients already", rather than blocke
You are missing a back quote here:
```suggestion
- `PGPOOL_RESERVED_CONNECTIONS`: When this parameter is set to 1 or greater, incoming connections from clients are not accepted with error message "Sorry, too many clients already", rather than blocked if the number of current connections from clients is more than (num_init_children - reserved_connections). Defaults to `0`.
```

2021-12-14 23:04 UTC, meln5674 commented on README.md
> +- `PGPOOL_RESERVED_CONNECTIONS: When this parameter is set to 1 or greater, incoming connections from clients are not accepted with error message "Sorry, too many clients already", rather than blocke
Should be good now, checked in browser before pushing this time (oops)

2021-12-20 11:14 UTC, rafariossaa commented
Hi,
  Thanks for the change.
  I am merging this.

2021-12-20 11:14 UTC, merged